// taro2.0.7/src/pages/home/index.jsx
import Taro, { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";

import "./index.css";

export default class Index extends Component {
  constructor(props) {
    super(props);
    this.state = {
      listData: []
    };
  }

  config = {
    navigationBarTitleText: "taro2.0.7版",
    enablePullDownRefresh: true,
    backgroundTextStyle: "dark"
  };

  render() {
    return (
      <View>
        <Button onClick={this.gotoProduct.bind(this)}>商品列表</Button>
      </View>
    );
  }
  gotoProduct() {
    Taro.navigateTo({
      url: "/pages/product/index"
    });
  }
}

// uni-app/src/pages/home/index.vue
<template>
  <view>
    <button @click="gotoProduct()">商品列表</button>
  </view>
</template>

<script>
export default {
  data() {
    return {};
  },
  onLoad() {},
  methods: {
    gotoProduct: function(e) {
      uni.navigateTo({ url: "/pages/product/index" });
    },
  },
};
</script>

<style></style>
